# Generated by Django 3.0.5 on 2020-04-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='query',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
